version: '3.9'
services:
  mongo:
    image: mongo:7.0.3
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USER:?}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASS:?}
    volumes:
      - /data/db
    ports:
      - "27017:27017"
  mongo-express:
    image: mongo-express:1.0.0-20
    restart: always
    ports:
      - "8081:8081"
    environment:
      ME_CONFIG_BASICAUTH_USERNAME: ${MONGO_EXPRESS_USER:?}
      ME_CONFIG_BASICAUTH_PASSWORD: ${MONGO_EXPRESS_PASS:?}
      ME_CONFIG_MONGODB_URL: mongodb://${MONGO_USER:?}:${MONGO_PASS:?}@mongo:27017/