version: '3.9'
services:
  app:
    image: ${APP_IMAGE:?}
    depends_on:
      - clickhouse
    ports:
      - "8080:8080"
    environment:
      SERVER_ADDRESS: ${SERVER_ADDRESS:?}
      AUTH_USER: ${AUTH_USER:?}
      AUTH_PASS: ${AUTH_PASS:?}
      CLICKHOUSE_DB: ${CLICKHOUSE_DB:?}
      CLICKHOUSE_HOST: clickhouse
      CLICKHOUSE_PORT: 9000
      CLICKHOUSE_USER: ${CLICKHOUSE_USER:?}
      CLICKHOUSE_PASS: ${CLICKHOUSE_PASS:?}
  clickhouse:
    image: clickhouse/clickhouse-server:23.9
    environment:
      CLICKHOUSE_DB: ${CLICKHOUSE_DB:?}
      CLICKHOUSE_USER: ${CLICKHOUSE_USER:?}
      CLICKHOUSE_DEFAULT_ACCESS_MANAGEMENT: 1
      CLICKHOUSE_PASSWORD: ${CLICKHOUSE_PASS:?}
    cap_add:
      - NET_ADMIN
      - IPC_LOCK
    volumes:
      - clickhouse_data:/var/lib/clickhouse/
    ports:
      - "18123:8123"
      - "19000:9000"
volumes:
  clickhouse_data: