version: '3.9'
services:
  clickhouse:
    image: clickhouse/clickhouse-server:23.9
    environment:
      CLICKHOUSE_DB: ${CLICKHOUSE_DB:?}
      CLICKHOUSE_DEFAULT_ACCESS_MANAGEMENT: 1
      CLICKHOUSE_USER: ${CLICKHOUSE_USER:?}
      CLICKHOUSE_PASSWORD: ${CLICKHOUSE_PASS:?}
    cap_add:
      - NET_ADMIN
      - IPC_LOCK
    volumes:
      - clickhouse_data:/var/lib/clickhouse/
      - /var/log/clickhouse-server/
    ports:
      - "18123:8123"
      - "19000:9000"
volumes:
  clickhouse_data: